/*******************************************************************************
 * Copyright (c) 2015 Obeo.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 * 
 * Contributors:
 *     Obeo - initial API and implementation
 *******************************************************************************/
package org.eclipse.acceleo.query.tests.anydsl.validation;

import org.eclipse.acceleo.query.tests.anydsl.Country;

/**
 * A sample validator interface for {@link org.eclipse.acceleo.query.tests.anydsl.Adress}. This doesn't really
 * do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be
 * extended. This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AdressValidator {
	boolean validate();

	boolean validateZipCode(String value);

	boolean validateCity(String value);

	boolean validateCountry(Country value);
}
