<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="textualgame" nsURI="http://www.eclipse.org/acceleo/textualgame"
    nsPrefix="textualgame">
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialRoom" lowerBound="1"
        eType="#//Room"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialItems" upperBound="-1"
        eType="#//Item"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" lowerBound="1" upperBound="-1"
        eType="#//Room" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//Item" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1"
        upperBound="-1" eType="#//RoomState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultState" lowerBound="1"
        eType="#//RoomState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoomState" eSuperTypes="#//NamedElement #//IllustratedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isActive" eType="#//Condition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true" interface="true"
      eSuperTypes="#//NamedElement #//ConditionalElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalElement" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOneTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isVisible" eType="#//Condition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isEnabled" eType="#//Condition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IllustratedElement" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GotoRoom" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" lowerBound="1" eType="#//Room"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddItemsToInventory" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1" upperBound="-1"
        eType="#//Item"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Restart" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="InRoom" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" lowerBound="1" eType="#//Room"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasItems" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1" upperBound="-1"
        eType="#//Item"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InRoomState" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roomState" lowerBound="1"
        eType="#//RoomState"/>
  </eClassifiers>
</ecore:EPackage>
