<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="root" nsURI="http://www.eclipse.org/acceleo/aql/root" nsPrefix="rootpackage">
  <eClassifiers xsi:type="ecore:EClass" name="RootEClass" eSuperTypes="#//EntityInterface"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntityHolder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityInterfaces" upperBound="-1"
        eType="#//EntityInterface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityInterface" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="child" nsURI="http://www.eclipse.org/acceleo/aql/child" nsPrefix="childpackage">
    <eClassifiers xsi:type="ecore:EClass" name="ChildEClass" eSuperTypes="#//EntityInterface"/>
    <eSubpackages name="grand_child" nsURI="http://www.eclipse.org/acceleo/aql/grand-child"
        nsPrefix="grand_child_package">
      <eClassifiers xsi:type="ecore:EClass" name="GrandChildEClass" eSuperTypes="#//EntityInterface"/>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
