<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:ocl.ecore="http://www.eclipse.org/ocl/1.1.0/Ecore" name="mtlnonstdlib"
    nsURI="http://www.eclipse.org/acceleo/mtl/0.8.0/mtlnonstdlib.ecore" nsPrefix="mtlnonstdlib">
  <eClassifiers xsi:type="ecore:EClass" name="String">
    <eOperations name="replace" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String">
      <eAnnotations source="MTL non-standard"/>
      <eParameters name="substring" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
      <eParameters name="replacement" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
    </eOperations>
    <eOperations name="replaceAll" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String">
      <eAnnotations source="MTL non-standard"/>
      <eParameters name="substring" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
      <eParameters name="replacement" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
    </eOperations>
    <eOperations name="substituteAll" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String">
      <eAnnotations source="MTL non-standard"/>
      <eParameters name="substring" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
      <eParameters name="replacement" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
    </eOperations>
    <eOperations name="startsWith" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/Boolean">
      <eAnnotations source="MTL non-standard"/>
      <eParameters name="substring" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
    </eOperations>
    <eOperations name="endsWith" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/Boolean">
      <eAnnotations source="MTL non-standard"/>
      <eParameters name="substring" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
    </eOperations>
    <eOperations name="trim" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String">
      <eAnnotations source="MTL non-standard"/>
    </eOperations>
    <eOperations name="tokenize" eType="#//Sequence(String)">
      <eAnnotations source="MTL non-standard"/>
      <eParameters name="delimiters" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
    </eOperations>
    <eOperations name="contains" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/Boolean">
      <eAnnotations source="MTL non-standard"/>
      <eParameters name="substring" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OclAny">
    <eOperations name="eAllContents" eType="#//Sequence(OclAny)">
      <eAnnotations source="MTL non-standard"/>
    </eOperations>
    <eOperations name="eAllContents" eType="#//Sequence(OclAny)">
      <eAnnotations source="MTL non-standard"/>
      <eParameters name="filter" eType="ocl.ecore:TypeType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/OclType"/>
    </eOperations>
    <eOperations name="ancestors" eType="#//Sequence(OclAny)">
      <eAnnotations source="MTL non-standard"/>
    </eOperations>
    <eOperations name="ancestors" eType="#//Sequence(OclAny)">
      <eAnnotations source="MTL non-standard"/>
      <eParameters name="filter" eType="ocl.ecore:TypeType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/OclType"/>
    </eOperations>
    <eOperations name="siblings" eType="#//Sequence(OclAny)">
      <eAnnotations source="MTL non-standard"/>
    </eOperations>
    <eOperations name="siblings" eType="#//Sequence(OclAny)">
      <eAnnotations source="MTL non-standard"/>
      <eParameters name="filter" eType="ocl.ecore:TypeType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/OclType"/>
    </eOperations>
    <eOperations name="eInverse" eType="#//Sequence(OclAny)">
      <eAnnotations source="MTL non-standard"/>
    </eOperations>
    <eOperations name="eInverse" eType="#//Sequence(OclAny)">
      <eAnnotations source="MTL non-standard"/>
      <eParameters name="filter" eType="ocl.ecore:TypeType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/OclType"/>
    </eOperations>
    <eOperations name="toString" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String">
      <eAnnotations source="MTL non-standard"/>
    </eOperations>
    <eOperations name="invoke" eType="ocl.ecore:AnyType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/OclAny">
      <eAnnotations source="MTL non-standard"/>
      <eParameters name="class" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
      <eParameters name="method" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
      <eParameters name="arguments" eType="#//Sequence(OclAny)"/>
    </eOperations>
    <eOperations name="current" eType="#//OclAny">
      <eAnnotations source="MTL non-standard"/>
      <eParameters name="index" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/Integer"/>
    </eOperations>
    <eOperations name="current" eType="#//OclAny">
      <eAnnotations source="MTL non-standard"/>
      <eParameters name="filter" eType="ocl.ecore:TypeType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/OclType"/>
    </eOperations>
    <eOperations name="getProperty" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String">
      <eAnnotations source="MTL non-standard"/>
      <eParameters name="key" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
    </eOperations>
    <eOperations name="getProperty" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String">
      <eAnnotations source="MTL non-standard"/>
      <eParameters name="key" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
      <eParameters name="arguments" eType="#//Sequence(OclAny)"/>
    </eOperations>
    <eOperations name="getProperty" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String">
      <eAnnotations source="MTL non-standard"/>
      <eParameters name="propertiesFileName" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
      <eParameters name="key" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
    </eOperations>
    <eOperations name="getProperty" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String">
      <eAnnotations source="MTL non-standard"/>
      <eParameters name="propertiesFileName" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
      <eParameters name="key" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
      <eParameters name="arguments" eType="#//Sequence(OclAny)"/>
    </eOperations>
    <eOperations name="eGet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eAnnotations source="MTL non-standard"/>
      <eParameters name="featureName" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Collection(T)">
    <eOperations name="sep" eType="#//Sequence(OclAny)">
      <eAnnotations source="MTL non-standard"/>
      <eParameters name="separatorString" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ocl.ecore:SequenceType" name="Sequence(String)" instanceClassName="java.util.List"
      elementType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/String"/>
  <eClassifiers xsi:type="ocl.ecore:SequenceType" name="Sequence(OclAny)" instanceClassName="java.util.List"
      elementType="ocl.ecore:AnyType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/OclAny"/>
  <eClassifiers xsi:type="ocl.ecore:BagType" name="Bag(OclAny)" instanceClassName="org.eclipse.ocl.util.Bag"
      elementType="ocl.ecore:AnyType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/OclAny"/>
</ecore:EPackage>
