/**
 *
 * $Id$
 */
package org.eclipse.acceleo.query.ast.validation;

import org.eclipse.acceleo.query.ast.Expression;

/**
 * A sample validator interface for {@link org.eclipse.acceleo.query.ast.Conditional}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConditionalValidator {
	boolean validate();

	boolean validatePredicate(Expression value);
	boolean validateTrueBranch(Expression value);
	boolean validateFalseBranch(Expression value);
}
