<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="profiler" nsURI="http://www.eclipse.org/acceleo/profiler/4.0"
    nsPrefix="profiler">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="This metamodel describes profile model elements. It can be extended by connector implementations to fit specific needs."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ProfileEntry">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This element describe the node of a profiling tree. To be useful after creation the method {@link ProfileEntry#start()} must be called when the profiler process starts. Then method {@link ProfileEntry#stop()} must be called at the end of the profiled process."/>
    </eAnnotations>
    <eOperations name="start"/>
    <eOperations name="stop"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The established time between the call to {@link ProfileEntry#start()} and the call to {@link ProfileEntry#stop()}."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callees" upperBound="-1"
        eType="#//ProfileEntry" containment="true" eOpposite="#//ProfileEntry/caller">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The list of {@link ProfileEntry} created between the call to {@link ProfileEntry#start()} and the call to {@link ProfileEntry#stop()} of &lt;code>this&lt;/code> object."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="caller" eType="#//ProfileEntry"
        unsettable="true" eOpposite="#//ProfileEntry/callees">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The parent {@link ProfileEntry}."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The number of times this {@link ProfileEntry} has been {@link ProfileEntry#start() used}."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitored" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The {@link EObject} representing the profiled process."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The percentage of time spent in this {@link ProfileEntry} based on the root {@link ProfileEntry} {@link ProfileEntry#getDuration() duration} ."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The creation time of this {@link ProfileEntry}. It's managed by the {@link ProfileEntry} itself."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProfileResource">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The root {@link ProfileEntry} container. Can be extended by connectors to fit needs."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" eType="#//ProfileEntry"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The root {@link ProfileEntry}."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
